version: '3'

services:
  api1: &app
    image: api-rinha-spring
    hostname: api1
    build: .
    depends_on:
      - db
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://localhost:5432/postgres?currentSchema=rinha
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.7GB'
    network_mode: host

  api2:
    <<: *app
    hostname: api2
    environment:
      - SERVER_PORT=8081
      - DATABASE_URL=jdbc:postgresql://localhost:5432/postgres?currentSchema=rinha

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'

  db:
    image: postgres
    container_name: rinha-backend-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'postgres'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.4GB'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: host